In [1]:
import torch
import numpy as np

## Creating Tensors 

In [5]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float) # retains the properties of x_data
print(f"Rand Tensor : \n {x_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Rand Tensor : 
 tensor([[0.0555, 0.4092],
        [0.2123, 0.3644]]) 



In [8]:
shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n{rand_tensor} \n")
print(f"Ones Tensor : \n{ones_tensor}\n")
print(f"Zeros Tensor : \n{zeros_tensor}\n")

Random Tensor : 
tensor([[0.7117, 0.8759, 0.0263],
        [0.9632, 0.0577, 0.6430]]) 

Ones Tensor : 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor : 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



## Attributes of Tensor

In [9]:
tensor = torch.rand(3,4)

print(f"Shape of Tensor : {tensor.shape}")
print(f"Datatype of Tensor : {tensor.dtype}")
print(f"Device of Tensor : {tensor.device}")

Shape of Tensor : torch.Size([3, 4])
Datatype of Tensor : torch.float32
Device of Tensor : cpu


## Operations on Tensor

In [10]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]], device='cuda:0')


In [14]:
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [15]:
y2 = torch.matmul(tensor, tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

In [17]:
z1 = torch.mul(tensor, tensor)
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')

In [19]:
agg = tensor.sum()
agg.item()

12.0

In [20]:
t3 = tensor.add(5)
t3

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]], device='cuda:0')